services:
  postgres:
    image: postgres:15.8-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financeaidb
    ports:
      - 5432:5432
    volumes:
      - .docker/data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres
